#!/bin/bash -eu -o pipefail


cleanup-repo() {
    # Clean out old copy of repo.
    #
	# Remove file or directory if it exists.
    # Succeed if successful, or if it was never even there.

    repo=$1
	if [ -e $repo ]; then          # make sure it's gone
		rm -r $repo                # remove it
	fi
}

all_repos="scratch itchy scratchy scratch.git"
remove-old-repos() {
	# Remove any old repos.
	for repo in $all_repos; do
		cleanup-repo $repo
	done
}

make-scratch() {
    # Make a minimal scratch repo.
    #
    # Tagging the very first commit is always a good idea
    # You can find it with `git checkout $(git rev-list --all --reverse | head -1)`,
    # but `git checkout initial` is easier to remember. :-)
    git init --quiet scratch           # make a scratch directory, under Git version control
    pushd scratch > /dev/null          # go there
    touch .gitkeep                     # a hidden, empty file, to make something to add and commit.
    git add .gitkeep                   # mark it for commitment,
    git commit -q -m"Initial commit"   # and commit it!
    git tag initial                    # tag the first commit
    popd > /dev/null                   # get back, Jojo
}

make-simple-branch() {
    # Make a simple branching structure
    #
    # - one branch
    # - one commit in each branch
    # - one conflict: different text on same line in README.md
    # - ends in master branch

    pushd scratch > /dev/null                                          # go there
    branchname=davidian                                                 # q.v.
    git checkout --quiet -b $branchname                                 # make a new branch
    echo "# Scratch branch $branchname for exploring Git" > README.md   # give it a README
    git add .                                                           # add "everything new/changed"
    git commit -q -m"Add README.md for branch $branchname"              # descriptive commit message
    git checkout --quiet -                                              # checkout the previous branch
    echo "# Scratch repo for exploring Git" > README.md                 # README for master branch
    git add .                                                           # add "everything new/changed"
    git commit -q -m"Add README.md"                                     # another descriptive message
    popd > /dev/null                                                    # get back, Jojo
}


if [[ $BASH_SOURCE == $0 ]]; then
    echo "Here I am!"
fi
